logging:
  level: DEBUG
  
model:
  name: LLaMA-7b-chat
  path: ../model/Llama-2-7b-chat.gguf

acceleration:
  useGPU: True
  GPU: mps 

RAG:
  source_path: ../assets/RAG Documents/
  EMBEDDINGS_MODEL_NAME: all-MiniLM-L6-v2
  TARGET_SOURCE_CHUNKS: 4
  chunk_size: 500
  chunk_overlap: 50
