logging:
  level: DEBUG
  
model:
  name2: Meta-Llama-3-8B-Instruct-Q8_0
  name: LLaMA-7b-chat
  name3: Llama-2-7b-chat-medvet
  path: ../model/Llama-2-7b-chat.gguf
  path2: ../model/tiiuae-falcon-7b-Q6_K.gguf
  path3: ../model/Meta-Llama-3-8B-Instruct-Q8_0.gguf
  path4: ../model/Llama-2-7b-chat-medvet.gguf

acceleration:
  useGPU: True
  GPU: mps 

RAG:
  source_path: ../assets/RAG Documents/
  EMBEDDINGS_MODEL_NAME: all-MiniLM-L6-v2
  TARGET_SOURCE_CHUNKS: 4
  chunk_size: 500
  chunk_overlap: 50
