logging:
  level: DEBUG
  
model:
  name: Meta-Llama-3-8B
  path: ../model/Meta-Llama-3-8B

acceleration:
  useGPU: True
  GPU: mps 

RAG:
  source_path: ../assets/Documents/MM_Rag/
  EMBEDDINGS_MODEL_NAME: all-MiniLM-L6-v2
  TARGET_SOURCE_CHUNKS: 4
  chunk_size: 500
  chunk_overlap: 50
