logging:
  level: DEBUG
  
model:
  name1: Meta-Llama-3-8B-Instruct
  name: LLaMA-7b-chat
  path1: ../model/Meta-Llama-3-8B-Instruct
  path: ../model/Llama-2-7b-chat.gguf
  path2: ../model/tiiuae-falcon-7b-Q6_K.gguf
  path3: ../model/LlaMA_3_813b_instruct_Q8.gguf

acceleration:
  useGPU: True
  GPU: mps 

RAG:
  source_path: ../assets/RAG Documents/
  EMBEDDINGS_MODEL_NAME: all-MiniLM-L6-v2
  TARGET_SOURCE_CHUNKS: 4
  chunk_size: 500
  chunk_overlap: 50
